pull_request_rules:
  - name: Automatic merge on review
     # https://doc.mergify.io/examples.html#require-all-requested-reviews-to-be-approved
    conditions:
      - "#changes-requested-reviews-by=0"
      - base=master
      - label=approval + 2
      - label!=WIP
      - check-success=my favorite ci
    actions:
      merge:
        method: merge
      delete_head_branch:
      
  - name: Add Label approval + 1
    conditions:
      - "#approved-reviews-by=1"
      - label!=WIP
    actions:
      label:
        add: ["approval + 1"]

  - name: Add Label approval + 2
    conditions:
      - "#approved-reviews-by=2"
      - label!=WIP
    actions:
      label:
        add: ["approval + 2"]
        remove: ["approval + 1"]

  - name: Add Label needs reveiw
    conditions:
      - "#changes-requested-reviews-by=0"
      - label!=WIP
    actions:
      label:
        add: ["needs review"]
